server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_event
  application:
    name: ms-event-management

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

