server:
  port: 8080

spring:
  application:
    name: ms-event-management
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/db_event?authSource=admin

ticket-management:
  url: http://localhost:8081/br/com/compass/ticketmanagement/v1

springdoc:
  api-docs:
    path: /event-docs
  swagger-ui:
    path: /swagger-ui.html
